[tool.poetry]
name = "hypn0"
version = "0.1.0"
description = "hypn0 - Гипонтические SVG"
authors = ["erjemin <erjemin@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "hypn0", from = "hypn0" },
#    { include = "hypn0-site", from = "hypn0" },
]

[tool.poetry.dependencies]
python = "^3.14"
pillow = "^12.3.0"
django = "^6.0.8"
django-environ = "^0.14.0"
hashids = "^1.3.1"
gunicorn = "^26.0.0"
whitenoise = "^6.12.0"
etpgrf = "^0.1.6.post1"
pytils = "^0.4.4"

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
