# Generated by Django 6.1 on 2026-08-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypn0_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbvote',
            options={'ordering': ['-d_created_at'], 'verbose_name': 'Голос/Лайк', 'verbose_name_plural': 'Голоса/Лайки'},
        ),
        migrations.AlterField(
            model_name='tbblogpost',
            name='id',
            field=models.SmallAutoField(help_text='Первичный ключ (SmallAutoField, до 32 767 записей)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='i_claims_count',
            field=models.PositiveIntegerField(default=0, help_text='Число жалоб на гипнотическую SVG-картину. Поле используется для отображения в интерфейсе. Для расчета рейтинга популярности намеренно НЕ ИСПОЛЬЗУЕТСЯ. Рейтинг будет рассчитан на основе таблицы <tt>Голоса/Лайка</tt> с учетом весов лайков и клаймов.', verbose_name='Число жалоб'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='i_level',
            field=models.IntegerField(choices=[(0, 'Candidate: Шум сознания'), (10, 'Voted: Плеск бессознательного'), (30, 'Moderated: Одобрено Мозговым Слизнем'), (1000, 'Locked: Глубокий транс'), (-20, 'Шейминг (аномальный наплыв жалоб)'), (-10, 'Подозрение на накрутку (спайк лайков)')], default=0, help_text='Уровень', verbose_name='В какой группе находится SVG-файл генерации'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='i_likes_count',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Число лайков гипнотической SVG-картины. Поле используется для отображения в интерфейсе. Для расчета рейтинга популярности намеренно НЕ ИСПОЛЬЗУЕТСЯ. Рейтинг будет рассчитан на основе таблицы <tt>Голоса/Лайка</tt> с учетом весов лайков и клаймов.', verbose_name='Число лайков'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='i_views_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Число просмотров'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='id',
            field=models.AutoField(help_text='Первичный ключ (~2.14 млрд записей, 4 байта)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='s_hash_id',
            field=models.CharField(editable=False, max_length=16, unique=True, verbose_name='ID-Хэш'),
        ),
        migrations.AlterField(
            model_name='tbvote',
            name='i_direction',
            field=models.IntegerField(choices=[(1, 'Like (+1)'), (-2, 'Claim (-2)'), (2, 'Author Like (+2)')], default=1, help_text='Направление голоса', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='tbvote',
            name='id',
            field=models.BigAutoField(help_text='Первичный ключ (BigAutoField, 8 байт)', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
