# Generated by Django 6.1 on 2026-09-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypn0_site', '0002_alter_tbvote_options_alter_tbblogpost_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbhypn0item',
            name='i_file_size',
        ),
        migrations.AlterField(
            model_name='tbblogpost',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='URL-слаг'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='f_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Рейтинг для Smart Retention и определения, что удалять при чистке по лимитам, а что оставлять', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='i_claims_count',
            field=models.PositiveIntegerField(default=0, help_text='Число жалоб на гипнотическую SVG-картину. Поле используется для отображения в интерфейсе. Для расчета рейтинга популярности намеренно НЕ ИСПОЛЬЗУЕТСЯ. Рейтинг будет рассчитан на основе таблицы <tt>Голоса/Лайка</tt> с учетом весов лайков и клаймов.', verbose_name='Жалоб'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='i_level',
            field=models.IntegerField(choices=[(0, 'Candidate: Шум сознания'), (10, 'Voted: Плеск бессознательного'), (30, 'Moderated: Одобрено Мозговым Слизнем'), (1000, 'Locked: Глубокий транс'), (-20, 'Шейминг (аномальный наплыв жалоб)'), (-10, 'Подозрение на накрутку (спайк лайков)')], default=0, help_text='В какой группе находится SVG-файл генерации', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='i_likes_count',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Число лайков гипнотической SVG-картины. Поле используется для отображения в интерфейсе. Для расчета рейтинга популярности намеренно НЕ ИСПОЛЬЗУЕТСЯ. Рейтинг будет рассчитан на основе таблицы <tt>Голоса/Лайка</tt> с учетом весов лайков и клаймов.', verbose_name='Лайков'),
        ),
        migrations.AlterField(
            model_name='tbhypn0item',
            name='i_views_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Просмотров'),
        ),
    ]
