# Generated by Django 6.1 on 2026-09-02 22:00

import hypn0_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypn0_site', '0003_remove_tbhypn0item_i_file_size_alter_tbblogpost_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbhypn0item',
            name='file_svg',
            field=models.FileField(help_text='Результирующий SVG-файл генерации', upload_to=hypn0_site.models.hypn0_svg_upload_to, verbose_name='SVG-файл'),
        ),
    ]
